apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx
      annotations:
        multicluster.admiralty.io/elect: ""
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
